### ISSUE TITLE
"use multi beats" make scheduler incorrect 

### ISSUE THREAD

**Issue by xiaobaidemu** [MnogoByte/celery-redundant-scheduler#1]
hello,
     I find when I use three "celery-redundant-scheduler" beat for test，there will be “confusion” which after few minutes the tasks will often delay.
For example， a task A need be scheduled every 60 seconds，but after 10min, the task maybe delay one or two even more minutes to scheduled.
I read the source code but found nothing. 
I would really appreciate if you find same issue .
Thank you

**Comment by atin65536** [comment]
Can you send more details?
Wich Celery version you use?
Your Celery config and Your celerybeat running method (supervisor, systemd, etc) may be also helpful.

**Comment by xiaobaidemu** [comment]
I use the Celery version 4.2.1 (maybe the version is too high, because the last commit of this project is 3 years age, but I think the version is ok。)
I use supervisor to start celery worker（16 worker。worker actually do nothing, return None directly， because I just want to test the beat is correct）。
I  start three beat processes in one machine to simulate that multi machines start multi beat .
CMD:
    nohup celery -A mySchedule beat --scheduler=celery_redundant_scheduler.scheduler.RedundantScheduler --loglevel=DEBUG --max-interval=1 --pidfile=beat1.pid >> beat1.log 2>&1 &
   nohup celery -A mySchedule beat --scheduler=celery_redundant_scheduler.scheduler.RedundantScheduler --loglevel=DEBUG --max-interval=1 --pidfile=beat2.pid >> beat2.log 2>&1 &
  nohup celery -A mySchedule beat --scheduler=celery_redundant_scheduler.scheduler.RedundantScheduler --loglevel=DEBUG --max-interval=1 --pidfile=beat3.pid >> beat3.log 2>&1 &

 the module "mySchedule" contain all periodic tasks（180+ different periodic tasks, every task has different interval time, for example every 60s, 20s 300s etc. to be scheduled ）there will be 5000+ tasks in one hour which should be schedule。

There is a  issue which I think probably make the scheduler . Let me give you a example。
We assume，Task A should be scheduled every 60s ，Task B should be scheduled every 65s 
In the tick function in Class Scheduler， the tick will get "last_run_at" of Task A which is at the top of Min Heap H in redis.  if  the Task  should have been scheduled in Time "t"，but when actually in "t + 0.5" , the beat 1  begin to check the "last_run_at" of  Task A ，then it found Task A has been scheduled at ”t+0.2“ by other beat 2 . So then the Task A is not due, beat will sleep 59.5s. But in this 59.5 , Task B may should be wake up in t+5.2s to test whether B should be scheduled, but because the beat process has sleep 59.5s, so the Task B may delay try to be scheduled.
Sorry for my English, but I have try my best to explain my point， Hope you can understand me
PS: Thanks for your reply

**Comment by atin65536** [comment]
This package tested with celery version 3.1.24 and used in prodaction for years, and works fine.
Actualy, Your problem may be to high celery version.
This package injects several monkey patches in celery core. In case of core logic modified, it causes errors and unstable working.
Besides, I don't receive information about broker type You use. This package tested only with RabbitMQ broker.

**Comment by xiaobaidemu** [comment]
I check the source code of beat between 3.1 and 4.2 in celery. It is really a big difference. The way and data structure for store schedules is difference （3.1 list vs 4.2 heap）.The problem should be my celery version is too high.
Will you test the celery-redundant-scheduler and modify this package using celery 4.2 or higher level in the future？

**Comment by atin65536** [comment]
Unfortunately, I have no time resourses to do this. But You are welcome to fix this problem and make pull request.

**Comment by xiaobaidemu** [comment]
Thank you for your reply. If I have spare time, I hope I can try to figure out.
